export const enum FormName {
  Present,
  PresentPol,
  Negative,
  NegPol,
  Past,
  PastPol,
  NegPast,
  NegPastPol,
  Te,
  TeReq,
  NegTe,
  NegReq,
  Naide,
  Zu,
  PotentialFull,
  PotentialShort,
  NegPotentialFull,
  NegPotentialShort,
  Passive,
  NegPassive,
  Causative,
  NegCausative,
  CausPassive,
  NegCausPassive,
  Imperative,
  NegImperative,
  Nasai,
  Volitional,
  VolitionalPol,
  BaConditional,
  NegBaConditional,
  TaraConditional,
  NegTaraConditional
}

export const enum FormType {
  a, i, u, e, o, t
}

export type formInfo = {form: FormName, name: string, type: FormType};

export const allVerbForms: { [index: string]: formInfo } = {
  present:            {form: FormName.Present, name: "Present plain",                          type: FormType.u},
  presentPol:         {form: FormName.PresentPol, name: "Present polite",                      type: FormType.i},
  negative:           {form: FormName.Negative, name: "Negative plain",                        type: FormType.a},
  negPol:             {form: FormName.NegPol, name: "Negative polite",                         type: FormType.i},
  past:               {form: FormName.Past, name: "Past plain",                                type: FormType.t},
  pastPol:            {form: FormName.PastPol, name: "Past polite",                            type: FormType.i},
  negPast:            {form: FormName.NegPast, name: "Negative past plain",                    type: FormType.a},
  negPastPol:         {form: FormName.NegPastPol, name: "Negative past polite",                type: FormType.i},
  te:                 {form: FormName.Te, name: "Te form",                                     type: FormType.t},
  teReq:              {form: FormName.TeReq, name: "Request",                                  type: FormType.t},
  negTe:              {form: FormName.NegTe, name: "Negative Te form",                         type: FormType.a},
  negReq:             {form: FormName.NegReq, name: "Negative request",                        type: FormType.a},
  naide:              {form: FormName.Naide, name: "Without ~",                                type: FormType.a},
  zu:                 {form: FormName.Zu, name: "Without ~ formal",                            type: FormType.a},
  potentialFull:      {form: FormName.PotentialFull, name: "Potential",                        type: FormType.e},
  potentialShort:     {form: FormName.PotentialShort, name: "Potential (short)",               type: FormType.e},
  negPotentialFull:   {form: FormName.NegPotentialFull, name: "Negative potential",            type: FormType.e},
  negPotentialShort:  {form: FormName.NegPotentialShort, name: "Negative potential (short)",   type: FormType.e},
  passive:            {form: FormName.Passive, name: "Passive",                                type: FormType.a},
  negPassive:         {form: FormName.NegPassive, name: "Negative passive",                    type: FormType.a},
  causative:          {form: FormName.Causative, name: "Causative",                            type: FormType.a},
  negCausative:       {form: FormName.NegCausative, name: "Negative causative",                type: FormType.a},
  causPassive:        {form: FormName.CausPassive, name: "Causative passive",                  type: FormType.a},
  negCausPassive:     {form: FormName.NegCausPassive, name: "Negative causative passive",      type: FormType.a},
  imperative:         {form: FormName.Imperative, name: "Imperative",                          type: FormType.e},
  negImperative:      {form: FormName.NegImperative, name: "Negative imperative",              type: FormType.u},
  nasai:              {form: FormName.Nasai, name: "Imperative (nasai)",                       type: FormType.i},
  volitional:         {form: FormName.Volitional, name: "Volitional",                          type: FormType.o},
  volitionalPol:      {form: FormName.VolitionalPol, name: "Volitional polite",                type: FormType.i},
  baConditional:      {form: FormName.BaConditional, name: "Conditional (eba)",                type: FormType.e},
  negBaConditional:   {form: FormName.NegBaConditional, name: "Negative conditional (eba)",    type: FormType.a},
  taraConditional:    {form: FormName.TaraConditional, name: "Conditional (tara)",             type: FormType.t},
  negTaraConditional: {form: FormName.NegTaraConditional, name: "Negative conditional (tara)", type: FormType.a},
}